### ISSUE TITLE
[BUG]: Driftwood giant throwing players under the map

### ISSUE THREAD

**Issue by ZapGamer** [XuuXiao/GiantSpecimens#13]
### Installation Method

Manual Download

### What happened?

I was spectating my friend while he was getting grabbed.
When he "touched the floor" he basically clipped through the map and it happened twice in a session on different maps (Artifice and Adamance).
We were playing on version v 2.1.1 with LLL on version v 1.2.1

### What did you do?

1. Got grabbed and thrown
2. Clipped through the map
3. Softlocked until I got teleported

### Version

v50

### What OS are you running?

Windows 10

### List of mods used

Here are the screenshots of the mods folders:
![plugin folder](https://github.com/XuuXiao/GiantSpecimens/assets/73616891/52843ae3-6c76-427b-a9d7-60deb763d979)
![patchers folder](https://github.com/XuuXiao/GiantSpecimens/assets/73616891/89c7debd-5ca6-4d02-b559-1a5b9a09690d)
![core folder](https://github.com/XuuXiao/GiantSpecimens/assets/73616891/faac4fc9-cbd0-4b87-b499-58eea83dccc7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Skyblade799** [comment]
Yeah I've been having this happen occasionally too. That, or "thrown", but I just end up slightly behind them.

**Comment by XuuXiaolan** [comment]
Fixed
