### ISSUE TITLE
[BUG]: Redwood movement stuck in place

### ISSUE THREAD

**Issue by DaisyAge12** [XuuXiao/GiantSpecimens#16]
### Installation Method

r2modman / r2mm

### What happened?

Every Redwood that spawns is stuck in it's spawn location unable to move. Whistle has no effect. Version 2.1.4 did not resolve this. 

### What did you do?

1. I hosted a match
2. We landed on outpost 31
3. The Redwood did not move

### Version

v50

### What OS are you running?

Windows 10

### List of mods used

Skinwalkers v5.0.0 
BepInExPack v5.4.2100 by BepInEx
LetMeLookDown v1.0.1 by FlipMods
OrbitRecharge v0.0.5 by mrov
AlwaysHearActiveWalkies v1.4.5 by Suskitech
LethalCompany_InputUtils v0.7.7 by Rune580
WalkieUse v1.5.0 by Renegades
FlashlightToggle v1.5.0 by Renegades
MoreCompany v1.9.1 by notnotnotswipez
Mimics v2.6.0 by x753
HookGenPatcher v0.0.5 by Evaisa
LethalLib v0.16.0 by Evaisa
LethalThings v0.10.4 by Evaisa
ShipLoot v1.1.0 by tinyhoot
PushCompany v1.2.0 by Midge
JumpDelayPatch v1.0.1 by monkes_mods
NoSellLimit v1.0.1 by ViViKo
LateCompany v1.0.13 by anormaltwig
EnemySoundFixes v1.3.0 by ButteryStancakes
LCMaxSoundsFix v1.2.0 by Hardy
loaforcsSoundAPI v1.0.12 by loaforc
LETHALRESONANCE v4.4.0 by LethalResonance
MaskedEnemyOverhaulFork v3.3.0 by Coppertiel
LethalModDataLib v1.2.2 by MaxWasUnavailable
FixPluginTypesSerialization v1.1.1 by Evaisa
StarlancerAIFix v3.6.0 by AudioKnight
LethalLevelLoader v1.2.4 by IAmBatby
PathfindingLagFix v1.2.1 by Zaggy1024
Overhaul_Moons v1.1.0 by Ssencipe
MoreBlood v1.0.2 by FlipMods
Helmet_Cameras v2.1.5 by RickArg
JesterStompShake v1.0.8 by Piggy
Scopophobia v1.1.2 by jaspercreations
OdinSerializer v2022.11.9 by Lordfirespeed
LethalNetworkAPI v2.2.0 by xilophor
Malfunctions v1.8.5 by zealsprince
CoilHeadStare v1.0.9 by TwinDimensionalProductions
RollingGiant v2.6.0 by NomnomAB
The_Fiend v1.0.5 by Rolevote
LobbyCompatibility v1.1.0 by BMX
SCPFoundationDungeon v4.3.0 by Badham_Mods
ImmortalSnail v0.7.4 by AmesBoys
LCSoundTool v1.5.1 by no00ob
FloodSnail v1.0.2 by Eiterbrocken
Backrooms v0.1.3 by Backrooms
LCUltrawide v1.1.1 by stefan750
AmberAlert v1.0.0 by gewdz
Tyler1Bracken v1.1.0 by SteamBlizzard
HoarderBugUseItems v1.0.3 by mattplays
LethalConfig v1.4.2 by AinaVT
TooManyEmotes v2.1.19 by FlipMods
 Runtime_Netcode_Patcher v0.2.5 by Ozone
More_Suits v1.4.3 by x753
Mod Logo
TooManySuits v1.1.0 by Verity
CullFactory v1.1.3 by fumiko
Black_Mesa_Half_Life_Moon_Interior v1.1.0 by Plastered_Crab
Dantors_Mental_Hospital v1.2.2 by Dantor
UnityMDK v1.3.0 by Saradora
LethalMDK v1.2.0 by Saradora
ScanTweaks v1.5.3 by Saradora
Gamer_Closet v1.4.0 by Omni024
Peter_Griffin_Suit v1.0.1 by yeahimliam
StormySuitPack v3.0.0 by GreenStorm64
ModelReplacementAPI v2.4.5 by BunyaPineTree
Thepostaldude v0.1.0 by Beeb
crosshair v1.0.1 by 
GeneralImprovements v1.2.8 by ShaosilGaming
StrangerThingsMod v0.0.32 by Scoliosis
JPOGTrex v1.0.7 by 347956
men_stalker v1.4.0 by YaBoiDucki
MoreInteriors v2.5.0 by Major_And_Skiz
Scoopys_Variety_Mod v1.2.0 by scoopy
GraphicsAPI v1.0.0 by IntegrityChaos
LCCutscene v1.0.0 by IntegrityChaos
Diversity v2.1.0 by IntegrityChaos
Outpost_31 v2.0.0 by LethalMatt
LethalToolbox v1.0.2 by IAmBatby
Wesleys_Moons v4.0.28 by Magic_Wesley
MrovLib v0.0.9 by mrov
TerminalFormatter v0.2.13 by mrov
DissonanceLagFix v1.0.0 by linkoid
SecretLabs v3.3.7 by Zingar
LetsGoDeeper v1.1.1 by TestAccount666
CoomfyDungeon v1.0.12 by Coomfy
MeteoMultiplier v1.1.3 by Fredolx
EnumUtils v1.0.3 by MegaPig
TheGiantSpecimens v2.1.4 by XuXiaolan
WesleysInteriors v1.1.17 by Magic_Wesley
WesleysInteriorsAddon v1.0.1 by Zehs

### Relevant log output

```PowerShell
[Error: Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack Trace:
EnemyAI.ChooseFarthestNodefromPosition (UnityEngine.Vector3 pos, System.Boolean avoidLineOfSight, System.Int32 Offset, System.Boolean log) (at <255c0877f9414c3aa6f1fe5079ac13f3>:IL_002F)
GiantSpecimens.Enemy.PinkGiantAI.SearchOrChaseTarget () (at ./src/PinkGiantAI.cs:246)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by XuuXiaolan** [comment]
Will post a fix soon

**Comment by DaisyAge12** [comment]
2.1.5 has resolved the issues! Thanks and great mod!
