### ISSUE TITLE
[BUG]: Redwood giants not despawning?

### ISSUE THREAD

**Issue by Skyblade799** [XuuXiao/GiantSpecimens#17]
### Installation Method

r2modman / r2mm

### What happened?

Seems like redwood giants are no longer despawning. I can hear them stomping in the ship, and they are still there on the next planet. 

### What did you do?

Went to a planet.
Redwood giant spawned. Finished and left (alive) and they were stomping around. Still visibly on the next planet, and still even  there at the company, at least audibly.

### Version

v50

### What OS are you running?

Windows 10

### List of mods used

Config code for R2ModMan: 01901ef4-812e-8925-8a5a-173c350067bd

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DaisyAge12** [comment]
This issue seems to be happening for me as well.

**Comment by XuuXiaolan** [comment]
Will find a fix soon, no problems should be occurring except redwood walking around, driftwood seems to be okay
