### ISSUE TITLE
什么时候支持lll

### ISSUE THREAD

**Issue by 1410677474** [XuuXiao/GiantSpecimens#3]
### Installation Method

r2modman / r2mm

### What happened?

加点新地牢就不能刷这怪了，新内部一般都是lll

### What did you do?

，，，，

### Version

v49

### What OS are you running?

Windows 10

### List of mods used

。。。。

### Relevant log output

```PowerShell
。。。
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by XuuXiaolan** [comment]
我知道这一点，在接下来的一两周内将发生重大变化来解决这个问题.
This is something I'm aware of, big change will happen to fix this within the next week or two.

**Comment by XuuXiaolan** [comment]
已通过新的 LL 更新修复，祝您玩得开心！
Fixed with the new LL update, have fun!
