### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by EchoLWS999** [XuuXiao/GiantSpecimens#6]
### Installation Method

r2modman / r2mm

### What happened?

I died through the wall on Artifice.

### What did you do?

1. I landed on Artifice
2. I hid in the narrow room in the side of the first warehouse on the left that has two openable doors because there were a lot of mobs
3. I died to a Redwood Giant that was on the other side of the wall as his foot ignored the wall between us.
4. I did not clip it, I apologize. You don't have v50 in the version list, I was in v50.

### Version

v49

### What OS are you running?

Windows 11

### List of mods used

Your "HOW" hyperlink navigates to a dead page. I hope this will suffice
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Theronguard-Emergency_Dice"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\TheWeavers-LethalBestiary"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\TheWeavers-NightmareFoxy"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\tinyhoot-ShipLoot"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\V_Power-FlashlightExtendedRange"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\veri-ShipWindows"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Woecust-Immersive_Visor"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Woecust-NoMorePush"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\x753-Mimics"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\xilophor-LethalNetworkAPI"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\XuXiaolan-TheGiantSpecimens"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Yoshify-DiscJockey"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Zaggy1024-NutcrackerFixes"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Zaggy1024-OpenBodyCams"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\zealsprince-Locker"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\zealsprince-Malfunctions"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Zehs-SellMyScrap"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\AbbyRawkz-Crowbar_Weapon"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\AgentRev-ShootableMouthDogs"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\AinaVT-LethalConfig"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\alexanderjoe-BiggeryBattery"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\AllToasters-SpectateEnemies"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\AmesBoys-ImmortalSnail"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\awithy-ModifiedCats"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Beauver-ExtraTerminalCommands"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\bigmcnugget-VanillaContentExpansion"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\BlueAmulet-LCBetterClock"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\BlueAmulet-NameFix"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\BMX-LobbyCompatibility"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Bobbie-NAudio"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Bobbie-UniTask"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\bozzobrain-BetterDoorWarning"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\ButteryStancakes-AccurateStaminaDisplay"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Caseuhdeeyuh-MolesterLootBug"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\CatsArmy-CorporateRestructureWeather"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Clementinise-CustomSounds"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Coppertiel-MaskedEnemyOverhaulFork"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\CTNOriginals-OuterDoorButtons"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\CustomSounds"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\den-Meltdown_Chance"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Dev1A3-ScannableCodes"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Drakorle-MoreItems"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Dreamweave-CompanyBuildingEnhancements"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\EchoLWS-EchosAdditionalSuits"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\EchoLWS-LETHALRESONANCEMODIFIED"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\EliteMasterEric-Coroner"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\ENZ-Lock_Doors_Mod"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Evaisa-FixPluginTypesSerialization"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Evaisa-HookGenPatcher"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Evaisa-LethalLib"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\ficcialfaint-Spectator_Voice_Icon_Fix"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\FlawTECH-DisableIntroSpeaker"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\FlipMods-HotbarPlus"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\FlipMods-ReservedFlashlightSlot"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\FlipMods-ReservedItemSlotCore"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\FlipMods-ReservedUtilitySlot"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\FlipMods-ReservedWalkieSlot"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\FlipMods-TooManyEmotes"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\freesnow-CollectYourDead"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\FutureGadgetsLab-WeightlessBoombox"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\FutureSavior-Hold_Scan_Button"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\gamehog44-LethalRadiation"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Hamunii-JetpackWarning"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Hardy-LCMaxSoundsFix"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Hexnet111-Excuse_me"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Hexnet111-SuitSaver"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Inoyu-Fast_Climbing"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Inoyu-Giant_Extension_Ladders"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\itsmeowdev-DoorFix"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\jaspercreations-Scopophobia"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\jockie-LethalExpansionCore"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\joe1359-LethalExtras"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Jordo-NeedyCats"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\JusteLoneWolf-MoreScraps"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Justice69-ImmersiveScraps"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\KawaiiBone-Remnants"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Kirpichyov-EnemiesScanner"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Kittenji-Groan_Tube_Scrap"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Kittenji-Herobrine"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Kittenji-NavMeshInCompany"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\LegoMaster3650-FairGiants"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\LethalAPI-LethalAPI_Terminal"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\loaforc-FacilityMeltdown"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\loaforc-loaforcsSoundAPI"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Lordfirespeed-OdinSerializer"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\MegaPiggy-EnumUtils"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Mhz-CrouchToStand"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\MikeMediaStudios-MikesTweaks"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\MMHOOK"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\MoonsweptTeam-Moonswept"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\MoreCompanyCosmetics"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\mrgrm7-LethalCasino"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\MrHydralisk-EnhancedLockpicker"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\MrHydralisk-MajorityVote"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\mrov-BetaWeatherTweaksBeta"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\mrov-LethalRichPresence"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\mrov-TerminalFormatter"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\no00ob-LCSoundTool"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\NotAtomicBomb-Terminal_Clock"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\NotAtomicBomb-TerminalApi"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Nyxchrono-DoorBreach"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Owen3H-CSync"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Owen3H-IntroTweaks"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Ozone-BepInUtils"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Ozone-Cabinet_Item_Storage"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Ozone-NC_LC_API"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Ozone-Runtime_Netcode_Patcher"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Pinta-PintoBoy"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\PloufJPEG-CompanyCreatures"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\PortableNavi-BetterInverseTeleporter"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\PXC-EnhancedSpectator"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\quackandcheese-ToggleMute"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\qwbarch-BarchLib"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\qwbarch-Mirage"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\readthisifbad-SnatchinBracken"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\red_eye-LethalAutocomplete"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\riverbible-LCAmmoCheck_OLD"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Rune580-LethalCompany_InputUtils"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Scintesto-Monster_Plushies"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Scintesto-Scavenger_Plushie"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Sconeys-abandonedcompanyassets"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Scoops-LethalPhones"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\ShaosilGaming-GeneralImprovements"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Sigurd-CSync"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Sligili-More_Emotes"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\snake_tech-HazardsOutside"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Sparble-FacelessStalker"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Spyci-CozyImprovements"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\Sv_Matt-HideModList"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\SylviBlossom-CustomWormTiming"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\SylviBlossom-SmartItemSaving"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\SYXZ-RadioNoPower"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\taffyko-BetterSprayPaint"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\taffyko-NiceChat"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\TheDeadSnake-Touchscreen"
"C:\Users\Echo\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Echo\BepInEx\plugins\TheFluff-FairAI"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by XuuXiaolan** [comment]
I'll send how I can improve the detection for the Redwood stomps, sorry about that!
