### ISSUE TITLE
[BUG]: When i come close to driftwood giant it makes me stuck

### ISSUE THREAD

**Issue by Mata0777** [XuuXiao/GiantSpecimens#7]
### Installation Method

r2modman / r2mm

### What happened?

I came close to the driftwood giant and got stuck

### What did you do?

2. We landed on Experimentation

### Version

v49

### What OS are you running?

Windows 10

### List of mods used

x753-Mimics-2.4.1
Theronguard-Emergency_Dice-1.1.16
FlipMods-TooManyEmotes-2.1.4
malco-Lategame_Upgrades-3.5.3
AudioKnight-StarlancerAIFix-3.5.0
Slam-TerminalPlus-1.0.2
loaforc-FacilityMeltdown-2.4.8
RT0405-TooManySuitsInWorldButtons-1.0.3
Verity-TooManySuits-1.0.9
LethalResonance-LETHAL_RESONANCE_MELTDOWN-1.1.6
BatTeam-LethalFashion-1.0.7
NiceHairs-Symbiosis-1.0.5
NotAtomicBomb-TerminalApi-1.5.3
RickArg-Helmet_Cameras-2.1.5
x753-More_Suits-1.4.3
AllToasters-SpectateEnemies-2.4.1
AlexCodesGames-AdditionalContentFramework-1.0.3
AlexCodesGames-AdditionalSuits-2.0.0
NiceHairs-NuclearLib-1.0.4
Sligili-More_Emotes-1.3.3
BepInEx-BepInExPack-5.4.2100
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.15.1
Hamunii-JetpackWarning-2.2.0
vasanex-ItemQuickSwitch-1.1.0
Rune580-LethalCompany_InputUtils-0.7.4
monkes_mods-JumpDelayPatch-1.0.1
Sligili-HDLethalCompany-1.5.6
Ozone-Runtime_Netcode_Patcher-0.2.5
Badham_Mods-SCPFoundationDungeon-3.0.0
FutureSavior-Hold_Scan_Button-1.1.1
Blorb-WeatherMultipliers-1.1.0
akechii-DiscountAlert-2.3.0
MegaPiggy-BuyableShotgun-1.1.0
MegaPiggy-BuyableShotgunShells-1.1.0
HGG-JigglePhysicsPlugin-1.1.2
JustJelly-AudibleDistanceLib-0.0.0
JustJelly-SubtitlesAPI-0.0.6
JustJelly-Subtitles-2.1.1
Ceelery-Kast-1.0.3
scoopy-LethalExtension-0.2.3
TwinDimensionalProductions-CoilHeadStare-1.0.9
Major_And_Skiz-MoreInteriors-2.5.0
scoopy-Scoopys_Variety_Mod-1.2.0
Alice-ScarletDevilMansion-1.3.7
JunLethalCompany-GamblingMachineAtTheCompany-1.3.5
FireNoobsta-Ducks_Moons-1.1.3
sfDesat-Aquatis-2.1.0
sfDesat-Orion-2.0.1
Boniato-Ganimedes-2.2.1
KayNetsua-E_Gypt_Moon-2.0.15
Magic_Wesley-Infernis-3.3.2
Magic_Wesley-Etern-3.3.2
Magic_Wesley-Acidir-4.2.3
sfDesat-Celest-1.0.7
Zingar-SecretLabs-3.3.7
quackandcheese-MinecraftTaigaMoon-1.1.1
Frostty-LC_Nuketown-1.0.0
ake-Dust2-2.0.0
Ryudious-Destiny_Islands-1.0.4
SeasideProject-Enceladus-1.2.0
boxofbiscuits97-QuotaRollover-2.3.0
Owen3H-CSync-3.0.1
BudgetAirpods-InsanityRemastered-1.1.2
Hardy-LCMaxSoundsFix-1.1.0
Bobbie-UniTask-2.5.0
Bobbie-NAudio-2.2.2
qwbarch-BarchLib-1.0.0
Drakorle-MoreItems-1.0.2
no00ob-LCSoundTool-1.5.1
Clementinise-CustomSounds-2.3.2
swny-WalkieRevamped-1.4.6
backendiain-KeyboardInventory-0.0.1
Renegades-FlashlightToggle-1.5.0
Hexnet111-SuitSaver-1.2.0
Lordfirespeed-OdinSerializer-2022.11.9
LethalMatt-Bozoros-1.0.1
FlipMods-BetterStamina-1.3.2
EliteMasterEric-Coroner-1.6.2
Jordo-NeedyCats-1.2.1
jaspercreations-Scopophobia-1.1.1
xilophor-LethalNetworkAPI-2.1.7
Piggy-LC_Office-1.1.25
Ccode_lang-SirenHead-1.4.3
Rolevote-The_Fiend-1.0.5
Astanpaeus-CreepyGirl-1.0.0
loaforc-loaforcsSoundAPI-1.0.10
BGN-PizzaTowerEscapeMusic-2.4.0
TheFluff-FairAI-1.3.4
Toskan4134-LethalRegeneration-1.3.0
Piggy-MaskedAIRevamp-0.2.1
MegaPiggy-InsanityMeter-1.0.0
Odyssey-OdysseySounds-1.3.2
ViViKo-SpectateDeathCause-1.0.0
Astanpaeus-CreepyJester-1.0.0
Fredolx-SignalTranslatorUpgrade-1.0.0
AinaVT-LethalConfig-1.4.1
Rocksnotch-CupboardFix-1.1.0
ficcialfaint-Spectator_Voice_Icon_Fix-1.0.0
Crazybloglog-Horrifying_Bracken-2.0.0
blink9803-DimmingFlashlights-1.0.1
skidz-PoolRooms-0.1.20
Dantor-Dantors_Mental_Hospital-1.2.2
Zaggy1024-PathfindingLagFix-1.2.1
SillySquad-Arachnophilia-1.8.1
Scintesto-Monster_Plushies-1.2.9
Scintesto-Scavenger_Plushie-1.0.9
ButteryStancakes-AccurateStaminaDisplay-2.0.2
DaXcess-NoMoreCompanyLogo-1.0.0
SillySquad-TakeThatMaskOff-2.1.6
Regis-ImmersiveCompany-0.3.0
Coppertiel-MaskedEnemyOverhaulFork-3.3.0
mrov-LethalRichPresence-0.5.8
Missing_Services-ReaperThumper-1.0.1
Orion-DontBlink-1.1.1
Pooble-LCBetterSaves-1.7.3
Solar32-PerformanceEnhancer-1.3.6
Renegades-WalkieUse-1.5.0
Nyxchrono-DoorBreach-1.1.0
F4ilS4fe-MaskTheDead-1.0.5
NomnomAB-TurretKey-1.2.1
FlipMods-HotbarPlus-1.6.3
linkoid-DissonanceLagFix-1.0.0
sunnobunno-YippeeMod-1.2.4
Zaggy1024-NutcrackerFixes-1.2.2
axd1x8a-LCAmmoCheck-1.1.1
fumiko-CullFactory-1.0.4
Hamunii-JetpackFallFix-2.0.1
Financier-GhostGirlFearReset-1.0.1
Danos-LethalStats-0.9.5
Lauriichan-FriendPatches-1.0.4
Rocksnotch-ShovelFix-1.1.0
AgentRev-ShootableMouthDogs-1.0.1
ViViKo-ItemClippingFix-1.1.4
Glitch-RankFix-1.0.2
taffyko-NameplateTweaks-1.0.6
Suskitech-AlwaysHearActiveWalkies-1.4.5
EliteMasterEric-SlimeTamingFix-1.0.2
FutureSavior-Boombox_Sync_Fix-1.1.2
Rozebud-FOV_Adjust-1.1.1
NutNutty-SellTracker-1.2.1
Zehs-Hitmarker-1.2.2
quackandcheese-ToggleMute-1.3.1
Aelstraz-BetterSpectator-1.2.0
CatsArmy-CorporateRestructureWeather-1.0.0
LeKAKiD-SignalTranslatorAligner-1.1.0
Hexnet111-Excuse_me-1.0.4
BlueAmulet-LCBetterClock-1.0.3
BlueAmulet-NameFix-1.0.1
5Bit-FPSSpectate-1.0.1
PuggerdGroup-ReignForest-1.3.0
BunyaPineTree-ModelReplacementAPI-2.4.4
sfDesat-ViewExtension-1.1.0
DeathWrench-FPSSpectate-1.0.4
Sigurd-CSync-4.1.0
Mhz-MoreHead-1.2.6
Sai-SaiCosmetics-1.1.0
fonnymunkey-SimpleHats-1.0.0
ExviiLe-ExviiLes_MoreCosmetics_pack-1.2.0
Justice69-ImmersiveScraps-1.2.0
EliteMasterEric-GarageDoorFix-1.0.0
itsmeowdev-DoorFix-1.0.0
readthisifbad-SnatchinBracken-1.5.0
Anubis-LaserControl-0.1.7
Dammsugare-KeepScrap-1.0.0
blink9803-AutoFlyToCompany-1.0.1
SolidStone-ShockwaveDroneEnemy-0.3.0
Zingar-Atlas_Abyss-1.1.8
SweetOnion-LethalSnap-1.5.7
AudioKnight-StarlancerMoons-1.4.2
Tolian-Celestria-0.5.9
sfDesat-Explorations-2.3.9
2Lethal4Company-SpringFactory-1.4.5
Scoliosis-StrangerThingsMod-0.0.32
TheDeadSnake-Touchscreen-1.1.2
XuXiaolan-TheGiantSpecimens-2.0.5
Magic_Wesley-Wesleys_Moons-3.1.10
Pinta-PintoBoy-2.0.0
lethal_coder-BetterCoilheadModel-1.1.4
zepsun-Conviction-0.0.4
Sparble-FacelessStalker-1.1.2
RosiePies-127_Eve-2.0.2
Guodan-Crest-1.1.2
Tolian-Zenit-0.2.3
RosiePies-59_Affliction-2.0.2
DeathWrench-DisableHelmetVisor-0.0.1
Evaisa-FixPluginTypesSerialization-1.1.1
Bobbie-FixRPCLag-1.0.1
Project_BlueFlame-Stable_Zap_Gun-1.1.0
Hotoni-TZPReworkedHealing-1.3.0
CatsArmy-SpaceSunShine-1.3.0
TheWeavers-NightmareFoxy-1.1.10
NomnomAB-RollingGiant-2.6.0
dotnet_lethal_company-NaCl_Net-0.1.1300
Ssencipe-Overhaul_Moons-1.0.2
jockie-LethalExpansionCore-1.3.15
Mellowdy-LightningRod-1.0.1
Sconeys-abandonedcompanyassets-0.15.79
TheWeavers-LethalBestiary-1.2.1
MegaPiggy-EnumUtils-1.0.3
veri-ShipWindows-2.0.5
veri-ShipWindows_4K_Skybox-1.0.2
YaBoiDucki-men_stalker-1.2.0
TestAccount666-PoisonPuffer-1.1.0
EliteMasterEric-WackyCosmetics-2.0.0
Hypick-MoreCosmetics-1.3.0
Evaisa-LethalThings-0.10.4
2018-LC_API-3.4.5
Vachon-Not_So_Brutal_Company-1.4.0
Garf-MissileTurrets-1.3.2
x753-Peepers-0.9.6
rhydiaan-NicerTeleporters-1.1.1
Wolf11221-SpaceShipDoor-1.0.1
RugbugRedfern-Skinwalkers-4.0.3
qwbarch-Mirage-1.5.3
darmuh-darmuhsTerminalStuff-3.0.4
notnotnotswipez-MoreCompany-1.8.1
BMX-LobbyCompatibility-1.1.0
XxnubnubxX-Better_Boom-1.0.2
Jamil-Corporate_Restructure-1.0.6
Unknown-Cheat Menu-0.0.0
Noop-UnityExplorer-4.8.2
stormytuna-EclipseOnly-1.0.0
MaxWasUnavailable-LethalModDataLib-1.2.2
Refract-LethalLevelLoaderFixed-1.1.0
LegoMaster3650-FairGiants-1.1.1

### Relevant log output

```PowerShell
https://nopaste.net/Ln0p4w9v0v
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by XuuXiaolan** [comment]
If you weren't the host then it's a known problem I'm working on fixing, sorry about that!

**Comment by Mata0777** [comment]
Hello i was playing singleplayer so i was the host
