### ISSUE TITLE
About Mr. Drifty 

### ISSUE THREAD

**Issue by Th3GamingDonkey** [XuuXiao/GiantSpecimens#8]
When scanning the Driftwood giant and checking the bestiary, it shows snare flea instead of the driftwood giant.

And another thing, what does the driftwood giant do, in detail?

**Comment by XuuXiaolan** [comment]
Uhhh mod list...?

**Comment by Th3GamingDonkey** [comment]
![image](https://github.com/XuuXiao/GiantSpecimens/assets/160597650/49fab16f-aa8f-4bdc-b12e-78fa5faa09c8)
![image](https://github.com/XuuXiao/GiantSpecimens/assets/160597650/b41b68b7-10a9-494b-b646-6cc3592468fb)
![image](https://github.com/XuuXiao/GiantSpecimens/assets/160597650/5259a2ea-9973-490d-8cec-c9e6f2126f29)
![image](https://github.com/XuuXiao/GiantSpecimens/assets/160597650/bcb72c19-243b-4453-bf2d-bc4c40f361d1)
![image](https://github.com/XuuXiao/GiantSpecimens/assets/160597650/090999ba-55ed-48bb-8472-c359f8fe4c85)

**Comment by XuuXiaolan** [comment]
That's likely an LLL bug, it should be fixed soon
