### ISSUE TITLE
[BUG]: Getting thrown Out of world when multiple redwood giant spawn at the same time

### ISSUE THREAD

**Issue by RedSun42** [XuuXiao/GiantSpecimens#9]
### Installation Method

r2modman / r2mm

### What happened?

Hello! Been messing up with a custom moon where I spawn a lot of redwood giant at the same time and the camera shake so much that I get thrown out of world even while inside the factory, would it be possible to have a config to remove the camera shake on spawn or prevent the effect from stacking :) 

Thanks!

### What did you do?

Spawn a lot of redwood giant at the same time
Enjoy (v50)

### Version

v49

### What OS are you running?

Windows 10

### List of mods used

should not Mather

### Relevant log output

```PowerShell
should not Mather
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by XuuXiaolan** [comment]
Camera shake is a distance thing that only happens when they're walking but ig I can turn it off through config, plus there's not meant to be more than 1 redwood!
